### PR TITLE
Astro-1168 Update Switch documentation (Storybook)

### PR DESCRIPTION
**Pull request by amalyah**
https://rocketcom.atlassian.net/browse/ASTRO-1168

Updated Switch description to match the new one on my UXDS branch.

### CODE REVIEW

**Comment by amalyah** [comment]
Ready for review by @Design-Kat @dmcalester @Cheshire89

**Comment by amalyah** [comment]
Note: Duncan says he can clean up all the extra updates that got added on to the PR for me.

**Review by Design-Kat — APPROVED** [review]
Amalya's addition looks good.

**Review by Cheshire89 — APPROVED** [review]

**Comment by dmcalester** [comment]
@dmcalester fix this nonsense

**Review by dmcalester — APPROVED** [review]

**Pull request merged**
