### PR TITLE
Astro 1201 slider

### PR DESCRIPTION
**Pull request by Cheshire89**
https://rocketcom.atlassian.net/browse/ASTRO-1201

update slider design 
update slider active thumb state
add ticks
adjust spacing of labels to ticks and track steps
use datalist instead of ol list for labels

### CODE REVIEW

**Review by cskerbo — CHANGES_REQUESTED** [review]
Can you add the link to the corresponding Astro ticket please?

**Review by dmcalester — CHANGES_REQUESTED** [review]
Some general notes

**Chrome**
The tick marks in Chrome overlay the track element and have a higher z-index than the thumb.
https://user-images.githubusercontent.com/60529018/109687199-dd3b4980-7b37-11eb-8d64-6a9201e77b08.mov

**Firefox**
Disabled state for both the thumb and track are displaying as active
Screen Shot 2021-03-02 at 9 12 36 AM

Similar to Chrome the tic marks have a higher z-index than the thumb and can be seen above the thumb when dragging
https://user-images.githubusercontent.com/60529018/109687719-618dcc80-7b38-11eb-8196-e30946a43df9.mov

**Safari**
The thumb is rendering above the track. Unknown if the tic mark have a higher z-index like Chrome & Firefox, but seems likely.
Screen Shot 2021-03-02 at 9 11 40 AM

**Comment by dmcalester** [comment]
Some general notes

**Chrome**
The tick marks in Chrome overlay the track element and have a higher z-index than the thumb.
https://user-images.githubusercontent.com/60529018/109687199-dd3b4980-7b37-11eb-8d64-6a9201e77b08.mov

**Firefox**
Disabled state for both the thumb and track are displaying as active
Screen Shot 2021-03-02 at 9 12 36 AM

Similar to Chrome the tic marks have a higher z-index than the thumb and can be seen above the thumb when dragging
https://user-images.githubusercontent.com/60529018/109687719-618dcc80-7b38-11eb-8196-e30946a43df9.mov

**Safari**
The thumb is rendering above the track. Unknown if the tic mark have a higher z-index like Chrome & Firefox, but seems likely.
Screen Shot 2021-03-02 at 9 11 40 AM

**Review by dmcalester — CHANGES_REQUESTED** [review]
Hey Sasha, sincere apologies I should have caught this first time through, but at the max of the range the slider thumb does not extend to the end of the range


https://user-images.githubusercontent.com/60529018/109834768-65345880-7bf7-11eb-8b12-5ad1cee1057d.mov

Screen Shot 2021-03-03 at 8 02 18 AM

**Comment by amalyah** [comment]
@Cheshire89 Could you have @Design-Kat review this PR instead of me since she did the UX changes for this one?

**Review by Design-Kat — CHANGES_REQUESTED** [review]
Three things I'm noticing:

1. The notches should only appear on the discrete slider (when there are multiple, pre-defined and distinct stopping points that are typically labelled), and not on the continuous slider (displays a range where there there are multiple stopping points along the range, such as a min/max). I'm noting them on all the sliders.
2. I noticed the same issue that Duncan did where the thumb doesn't go all the way to the end of the bar, I think this was one of the things we needed to talk about yet after the review last Friday, maybe we can chat about it this afternoon? (I noticed the labels are better centered over the notches though, they look great!)
3. I know there's a ticket out there to decouple the input from the sliders, I thought that was part of this ticket - is it being done with this one, or a different PR?

**Comment by dmcalester** [comment]
> 3. I know there's a ticket out there to decouple the input from the sliders, I thought that was part of this ticket - is it being done with this one, or a different PR?

At this time this is no longer a priority.

**Comment by Cheshire89** [comment]
@Design-Kat agreed passing criteria. Due to technical limitations we (Duncan, Amalaya and I ) agreed that for now we will not try implement tick marks as alignment becomes nightmarish
The main features for the slider. 

- Active dot on slider thumb when active
- slider height increase from 2 px to 3px
- Double check colors per design

**Comment by amalyah** [comment]
> @Design-Kat agreed passing criteria. Due to technical limitations we (Duncan, Amalaya and I ) agreed that for now we will not try implement tick marks as alignment becomes nightmarish
> The main features for the slider.
> 
> * Active dot on slider thumb when active
> * slider height increase from 2 px to 3px
> * Double check colors per design

Please confer with @Design-Kat regarding passing criteria since I was not the designer for this aspect and we should have consistency between the designs and the code (as well as what tickets will need to be created for later, if any).

**Comment by Design-Kat** [comment]
> @Design-Kat agreed passing criteria. Due to technical limitations we (Duncan, Amalaya and I ) agreed that for now we will not try implement tick marks as alignment becomes nightmarish
> The main features for the slider.
> 
> * Active dot on slider thumb when active
> * slider height increase from 2 px to 3px
> * Double check colors per design

Hi, @Cheshire89 Is this what we were going to chat about today? Please reach out to me so we can discuss this. If these discussions have already happened and decisions are final please consider including me on those chats in the future - it helps to know what I am reviewing when we review to know the backstory. Was the issue with the Thumb not going all the way to the end of the bar discussed? It is not appearing to work like a standard slider and this is still a concern to me if it's going to go live.

**Review by cskerbo — APPROVED** [review]

**Comment by Design-Kat** [comment]
@Cheshire89 is the "All Slider Variants" page a part of this ticket? If so, I noticed that the disabled slider still contains the discrete example, are we keeping that one? If so, the slider Thumb does not align, if it could be set to a value that aligns that would be great.

**Review by dmcalester — APPROVED** [review]

**Review by Design-Kat — APPROVED** [review]

**Pull request merged**
