### PR TITLE
Astro 1120 update icons

### PR DESCRIPTION
**Pull request by Cheshire89**
https://rocketcom.atlassian.net/browse/ASTRO-1120

update icon list with icons from latest Astro 6 Icons
move inline styles out of the template  + fix class styling syntax
remove title from rux-icon component as it may be undesired behavior for someone using the icon

### CODE REVIEW

**Comment by amalyah** [comment]
@Cheshire89 Icons are still showing outdated names. Example: "tm" was renamed to "atm" in the design files in the library master file.

**Review by amalyah — CHANGES_REQUESTED** [review]
Something happened. This isn't using the up-to-date icon file.

**Review by dmcalester — CHANGES_REQUESTED** [review]
The following icons are no longer rendering (seems most of the Astro ones basically). They appear to be rendering correctly in the next branch (https://next--astro-components.netlify.app/?path=/story/components-icons-symbols--all-icons) so seems a injection issue
- altitude
- antenna
- antenna-off
- antenna-receive
- antenna-transmit
- equipment
- payload
- processor
- satellite-off
- satellite-receive
- satellite-transmit
- timeline

**Comment by Cheshire89** [comment]
My sync failed which led to getting outdated file. It Should be fine now

**Review by dmcalester — APPROVED** [review]
Approved with merge conflict resolution.

**Review by amalyah — APPROVED** [review]

**Review by cskerbo — APPROVED** [review]

**Pull request merged**
