### PR TITLE
WIP: Astro-922:942:946 - Modal, Input, Pop-up KM Updates

### PR DESCRIPTION
**Pull request by im-cr**
**Jira Tickets:**
- 922 - https://rocketcom.atlassian.net/browse/ASTRO-922
- 942 - https://rocketcom.atlassian.net/browse/ASTRO-942
- 946 - https://rocketcom.atlassian.net/browse/ASTRO-946

**Changes:**
- Modal css/component update to km colors
- Input css
- popup css/component

**Questions:**

### CODE REVIEW

**Comment by dmcalester** [comment]
Start Here text is black, should be white. Applies to all current PRs https://deploy-preview-35--astro-components.netlify.app/?path=/story/astro-uxds-welcome--start-here
Screen Shot 2020-12-03 at 1 08 21 PM

**Comment by dmcalester** [comment]
Using this deploy preview https://deploy-preview-35--astro-components.netlify.app/?path=/story/components-dialog-box--dialog-box

Modal window not rendering correctly in dark mode
- No title bar background color
- No background color
- No border or border color
- Secondary button is using non KM button colors
- Primary button is using non KM button colors
- Border radius should be 2px

**Comment by im-cr** [comment]
> Start Here text is black, should be white. Applies to all current PRs https://deploy-preview-35--astro-components.netlify.app/?path=/story/astro-uxds-welcome--start-here
> Screen Shot 2020-12-03 at 1 08 21 PM

@amalyah commented on astro971 with update to default text color for dark theme. update has been added to astro-971

**Comment by im-cr** [comment]
> Using this deploy preview https://deploy-preview-35--astro-components.netlify.app/?path=/story/components-dialog-box--dialog-box
> 
> Modal window not rendering correctly in dark mode
> 
> * No title bar background color
> * No background color
> * No border or border color
> * Secondary button is using non KM button colors
> * Primary button is using non KM button colors
> * Border radius should be 2px (also in light mode)
> 
> Screen Shot 2020-12-03 at 11 48 35 AM

dark theme is missing modal style declaration variables. added now

**Comment by im-cr** [comment]
closing and splitting up ticket tasks

**Pull request closed without merging**
