### PR TITLE
Update rux-clock.js

### PR DESCRIPTION
**Pull request by gerhardatball**
* add tiny for a 1.0rem font-size
* add hideLabel to remove label

### CODE REVIEW

**Review by amalyah — APPROVED** [review]
If the team approves of the general concept, then I approve of the dev work. :)

**Review by cskerbo — APPROVED** [review]

**Comment by dmcalester** [comment]
@gerhardatball thank you for your submission.

The hide label feature has been approved by our UX and dev team.

The team had a couple of questions and some possible alternatives for the **tiny** variant. 

Could you detail your particular use case for tiny? In reviewing the execution it seems the font size is the same as the small variant, but the padding around the display has been reduced to zero. Is the tiny variant intended to fit the bounding height of a particular constraint and if so what is that height? Would it be possible to share a screen shot of its use case?

Second the dev team has suggested rather than making the `isTiny` a `boolean` using the same pattern as the button component and using a `size` attribute (https://astro-components.netlify.app/?path=/story/components-buttons--standard-button) since `isTiny` and `isSmall` are mutually exclusive options. 

I want to thank you again for your submission it really meant a lot to the team

**Comment by gerhardatball** [comment]
@dmcalester Thanks for the response!

I see I made a mistake in my original request. The height and font size should be reversed. That way you do still have some padding.

```
height: 1.15rem;
font-size: 1.0rem;
```
I think the suggestion of making `size` an attribute is a great idea. 

Having issues attaching screenshot right now will try again later or on Monday.

**Comment by dmcalester** [comment]
> @dmcalester Thanks for the response!
> 
> I see I made a mistake in my original request. The height and font size should be reversed. That way you do still have some padding.
> 
> ```
> height: 1.15rem;
> font-size: 1.0rem;
> ```
> 
> I think the suggestion of making `size` an attribute is a great idea.
> 
> Having issues attaching screenshot right now will try again later or on Monday.

Hey Gerhard, I was wondering if you’d had any luck with screen shots? I can reach out directly via email if that would be easier.

**Review by amalyah — CHANGES_REQUESTED** [review]
Pending further investigation from Duncan

**Comment by gerhardatball** [comment]
@dmcalester Sorry I forgot to reply. I can not share a screen shot at this time. The user interface has a very minimal footer, were we are messing around with placing the clock in the footer in the bottom right without the labels.

**Review by nortonprojects — CHANGES_REQUESTED** [review]
If this goes through next instead of master so we can track it with our usual release I'd be happy to approve

**Comment by nortonprojects** [comment]
Closing due to inactivity

**Pull request closed without merging**
