### PR TITLE
V2:Astro-966 - Notifications Font Style KM update

### PR DESCRIPTION
**Pull request by im-cr**
**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-966

**Changes** - commit: 
  - rux-notification.js
  - notifications.css
  - theme-dark
  - theme-light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/b460b56d-3c44-4397-be99-0b09d4b8a4c8/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed&s=notification)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/b460b56d-3c44-4397-be99-0b09d4b8a4c8/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=notification)

### CODE REVIEW

**Review by dmcalester — APPROVED** [review]
Approved, pending review by Amalya

**Comment by amalyah** [comment]
@carmenparks We have two sizes of notification banners designed, but it looks like we only have one version that's coded. Do you want me to follow the small or large banner designs for this review? (The code version appears to be a hybrid between the two.)

**Review by amalyah — CHANGES_REQUESTED** [review]
Pending Carmen's  confirmation on what design I should be comparing this too. Colors are good though. Remaining question is about desired font size and close icon.

**Review by cskerbo — APPROVED** [review]

**Comment by carmenparks** [comment]
> @carmenparks We have two sizes of notification banners designed, but it looks like we only have one version that's coded. Do you want me to follow the small or large banner designs for this review? (The code version appears to be a hybrid between the two.)

Let's go with the large Notification Banner since I would expect to see that first in a design system. The small Notification Banner will then need to be added in.

**Comment by im-cr** [comment]
@amalyah @carmenparks I'm going to merge this PR in since it accounts for the large notifications and we can circle back on the small notifications on stand up this week, if that's ok.

**Comment by amalyah** [comment]
> @amalyah @carmenparks I'm going to merge this PR in since it accounts for the large notifications and we can circle back on the small notifications on stand up this week, if that's ok.

For the large notification banner, the font should be the rem equivalent of 18px then. In the designs, the banner is 70px tall instead of the 68 px in code. Would it hurt anything to align the code with the design height?

**Comment by amalyah** [comment]
> > @carmenparks We have two sizes of notification banners designed, but it looks like we only have one version that's coded. Do you want me to follow the small or large banner designs for this review? (The code version appears to be a hybrid between the two.)
> 
> Let's go with the large Notification Banner since I would expect to see that first in a design system. The small Notification Banner will then need to be added in.

Ticket for adding small banner to code: https://rocketcom.atlassian.net/browse/ASTRO-1051

**Review by amalyah — CHANGES_REQUESTED** [review]
See general comments

**Comment by im-cr** [comment]
@amalyah updated height and font size of notification banner. Merging.

**Pull request merged**
