### PR TITLE
Astro-1140 - Progress Border Update

### PR DESCRIPTION
**Pull request by im-cr**
**Tickets**
- https://rocketcom.atlassian.net/browse/ASTRO-1140

**Changes** - commit: 
  - rux-progress.js
  - theme--dark.css

**Designs**
  - [Design](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/commits/56d1126b3464d40c0b57e72d73ce5d5eb2b4fb70/files/A86AC1CD-D207-4A1D-B7C0-80C938419411/layers/7B256175-0526-45CA-9B71-00CBE7586DCD?mode=build&selected=root-3EE65B33-7C1D-4EAB-869D-8281367BF2F7)

### CODE REVIEW

**Review by dmcalester — CHANGES_REQUESTED** [review]
- Border color doesn’t appear to be rendering. Seems the var is set properly in CSS in Safari, Chrome and Firefox
- Validate the light theme border is accurate to [design file](https://share.goabstract.com/3708bdad-0890-414f-8c44-ca28b6ade1ee?mode=design) looks grey in Storybook, but seems blue in design libs (#004872)

[See dark design files](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/commits/b03dbe89ed1b0b0044fbfd6eccaf5dd7efc1660d/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825/layers/7B256175-0526-45CA-9B71-00CBE7586DCD?mode=build&selected=root-3EE65B33-7C1D-4EAB-869D-8281367BF2F7).

Screen Shot 2021-01-20 at 11 25 45 AM

**Comment by im-cr** [comment]
@dmcalester updated variable for fix

**Comment by dmcalester** [comment]
> * Border color doesn’t appear to be rendering. Seems the var is set properly in CSS in Safari, Chrome and Firefox
> * Validate the light theme border is accurate to [design file](https://share.goabstract.com/3708bdad-0890-414f-8c44-ca28b6ade1ee?mode=design) looks grey in Storybook, but seems blue in design libs (#004872)

Light version still appears to be using the grey border, rather than the blue border defined in the design files.

**Review by dmcalester — CHANGES_REQUESTED** [review]
> * Border color doesn’t appear to be rendering. Seems the var is set properly in CSS in Safari, Chrome and Firefox
> * Validate the light theme border is accurate to [design file](https://share.goabstract.com/3708bdad-0890-414f-8c44-ca28b6ade1ee?mode=design) looks grey in Storybook, but seems blue in design libs (#004872)


Light version still appears to be using the grey border, rather than the blue border defined in the design files.

**Pull request merged**
